### ISSUE TITLE
Bad GCM token format assumption

### ISSUE THREAD

**Issue by avqdev** [rs/pushd#130]
I found that GCM token format can contain other characters than [a-zA-Z0-9_-] actually defined in the PushServiceGCM class: I've just been assigned a token containing the ':' (colon) character when registering, making my POST to /subscribers fail with error: "Invalid value for 'token'"

Adding the colon character to the regular expression in the PushServiceGCM class definition solved the issue; I could register and send push messages as usual.

Nevertheless, I did not find complete information about the format of this token (only a max length that some claim being able to grow to 4k), so there might be other characters that get in.

**Comment by jakubkrolewski** [comment]
Any update on this? What about the pull request?

**Comment by rs** [comment]
Merged

**Comment by jakubkrolewski** [comment]
Thanks a lot :)
