### ISSUE TITLE
GCM Automatic unregistration

### ISSUE THREAD

**Issue by m-kotek** [rs/pushd#133]
I'm having problems sending push notifications to my android device. As shown in the tutorial, i registered on the server with        
```
$ curl -d proto=gcm \
-d token=APA91bHzl-2xwg04x44p-Vx4WIXGJOXNFILiSvFaqRVcpxyES9yhKSfHI0H8W9RvI9l_rNHSu23W-LO14FAtNCNJbLXHVwF6N2pPPhlHfZ-0998P9E1CyHDyEnvID_qk2Hrf0U9a61ed \
-d lang=en \
-d badge=0 \
-d category=show \
-d contentAvailable=true \
http://localhost/subscribers
```
I got the token from my device using the phonegap-build/PushPlugin (regID variable)

```Javascript
switch( e.event )
    {
    case 'registered':
        if ( e.regid.length > 0 )
        {
            // Your GCM push server needs to know the regID before it can push to this device
            // here is where you might want to send it the regID for later use.
            console.log("regID = " + e.regid);
        }
    break;
```

When i register, i recieve the JSON structure with my ID and all the other stuff.
As next step i'll register to the sport event by `curl -X POST http://localhost/subscriber/m59X1-63MSM/subscriptions/sport`
The logging in the pushd console tells me that it registered the subscriber m59X1-63MSM to event sport.

But the next step won't work for me: when i try to execute `curl -d "title=AnyTitle&msg=AnyMsg" http://localhost/event/sport` 

Output in the pushd console:
```
silly: data = {"title":"AnyTitle","msg":"AnyMsg"}
silly: Title: AnyTitle
silly: AnyMsg
verbose: Pushed to 1 subscribers
verbose: 1 gcm subscribers
warn: GCM Automatic unregistration for subscriber m59X1-63MSM
verbose: Deleting event sport
verbose: Unsubscribed 0 subscribers from sport
```

Pushd automatically unregistered me, this happens every time i try to send a push notification.

Any ideas?
Thank you!

**Comment by akkina9** [comment]
I am seeing similar behavior.. I see "warn: GCM Automatic unregistration for subscriber XXXXXXX" every time I send an event.

**Comment by akkina9** [comment]
It is working now once we started using GCM Register ID. Before we were sending device id.

**Comment by m-kotek** [comment]
@akkina9 Sounds like you changed something on the client? Could you give me some more details?
Thank you!

**Comment by m-kotek** [comment]
Solved the Problem: We deleted the phonegap-build/PushPlugin and added the plugin `https://github.com/Telerik-Verified-Plugins/PushNotification.git` in Cordova, because the newest Version (2.5.0) of phonegap-build/PushPlugin didn't work for me. (I used the 2.4.0 Version)
Now push notifications work.
