### ISSUE TITLE
Not all iOS notification are deliver in sandbox

### ISSUE THREAD

**Issue by cermakjn** [rs/pushd#87]
Hi there,

I implemented pushd for our Android and iOS apps. There is a problem, when I tried to send notifications for all devices, sometimes push for iOS was not deliver, but in pushd seems it ok - there are no errors in log, all devices has been successfly added to subscribtion and all Android devices get it. Its about every third iOS pushd not deliver.

Any ideas?

Thank you!

**Comment by deweweire** [comment]
Did you find something about that ? i'm facing an issue that if you don't have internet for a while my push is not delivered
