### ISSUE TITLE
Are messages stored?

### ISSUE THREAD

**Issue by hadokee** [rs/pushd#93]
I'm using pushd for real-time message notification in webApp with EventStore. 
Now, I would implement a offrire facebook-like style notification system: if user received a message when He is offline He should See It in a "notifications" section with queue of the latest ten messages.
The question is: are the notification messages actually stored in redis? 
And if they are, are there methods in REST API to access them?

If they are not, it should be useful to implement a middleware that allows user to inject a store-message function.

**Comment by rs** [comment]
No, only subscriptions are stored.

**Comment by hadokee** [comment]
I suppose Google, iOS, WindowsPhone have their queue/notification service.
How to handle offline notification on webapps?

**Comment by tylkomat** [comment]
Just store them in your database and send a notification which links them to the notification. When the user is online he receives the notification, which updates some place in the dom to notify him. When the user is offline it is anyway stored in the database so the use will see it as usual.

The handling of the notification should just mimic the same DOM changes as the synchronous changes.
